name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  run-npm-test:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm run tests
